### ISSUE TITLE
Add the normalized call number to items

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/voyager_helpers#104]
We need the normalized call number from voyager in each item.  We are currently seeing the DISPLAY_CALL_NO in the json output https://bibdata.princeton.edu/bibliographic/5360031/items
Vs seeing both the display and the normalized.  Locator needs the normalized format.
```
<DISPLAY_CALL_NO>DK40 .A338 2007</DISPLAY_CALL_NO>
<NORMALIZED_CALL_NO>DK 40 A 338 2007</NORMALIZED_CALL_NO>
```

We believe it should be added here:
https://github.com/pulibrary/voyager_helpers/blob/26166ac7e68bfce5d5326f11c0a05933f2b07880/lib/voyager_helpers/liberator.rb#L173

**Comment by mzelesky** [comment]
The problem with this is the normalized call number is not found in the actual holding. This would require an additional Oracle call. What might be better would be developing a routine that normalizes the actual call number in the holdings record, instead of retrieving the normalized call number from a Voyager query.

**Comment by carolyncole** [comment]
@mzelesky Is there a known algorithm for the normalization?  From my quick google search it looks like it could be complex based on the format of the call number.

**Comment by mzelesky** [comment]
I'll submit a ticket to Ex Libris to describe the algorithm.
