### ISSUE TITLE
SCSB needs barcode lookup route that ignores bib & mfhd suppression

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/voyager_helpers#65]
The general barcode lookup route only returns bibliographic records and holdings records for unsuppressed bibs and holdings. SCSB needs to be able to retrieve data for all records attached to a given barcode.

**Comment by kevinreiss** [comment]
Added in voyager helpers under https://github.com/pulibrary/marc_liberation/pull/220/commits/cb3ecf0e011fdb96b99019e27b248a6501fd71f5. @tampakis would you rather see this in a new route a la

```https://bibdata-dev.princeton.edu/scsb/32101005029200```

rather than what it currently does with an additional parameter.

https://bibdata-dev.princeton.edu/barcode/32101005029200?recap=true

**Comment by tampakis** [comment]
yeah it's probably cleaner to establish a new route

**Comment by tampakis** [comment]
Can this be closed @kevinreiss?

**Comment by kevinreiss** [comment]
Yes, closing.
